17001222 -- Marian Vela

# Laboratorio No. 3

## Parte 1: Numpy

In [1]:
# imports relevantes para el lab

import numpy as np
import pandas as pd

1) ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [5]:
array1 = np.zeros( 1000, dtype = bool)
array1

In [8]:
print( "Tiene", array1.nbytes, "bytes" )

Tiene 1000 bytes


2) Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [12]:
# arange([start,] stop[, step,], dtype=None, *, like=None)
array_pares = np.arange( 100, 0, -2 )

In [13]:
print( array_pares[-10:] )

[20 18 16 14 12 10  8  6  4  2]


3) Dado el array
```
2 4 5 6
0 3 7 4
8 8 5 2
1 5 6 1
```
Seleccione con una instrucción el subarray de elementos
```
0 3 7 4
```
Después, seleccione el subarray de elementos
```
2 5
8 5
```

In [24]:
array2 = np.array([
    [2, 4, 5, 6],
    [0, 3, 7, 4],
    [8, 8, 5, 2],
    [1, 5, 6, 1]
])

In [16]:
subarray1 = array2[1, :]
subarray1

array([0, 3, 7, 4])

In [34]:
# escogemos fila 0, 2. Luego escogemos de ese resultado columna 0, 2.
subarray2 = array2[[0, 2], :][:, [0, 2]]
subarray2

array([[2, 5],
       [8, 5]])

4) Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], obtenga la media aritmética de la diferencia (a-b)

In [35]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

In [36]:
# media de diferencia
mean_dif = np.mean(a - b)
print("Promedio de diferencia:", mean_dif)

Promedio de diferencia: -0.25


5. Tengo valores de cordenadas (x, y) en las columnas del array
```
1.33 4.5
30.0 10.7
70.2 0.5
```
Agregue a este array las coordenadas (37.1, -3.6). Muestre en pantalla las dimensiones del nuevo array.

In [44]:
coordenadas = np.array([
    [1.33, 4.5],
    [30.0, 10.7],
    [70.2, 0.5]
])

In [45]:
coordenadas = np.append(coordenadas, [[37.1, -3.6]], axis = 0)
coordenadas

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.6 ]])

In [46]:
print("Dimensiones:", coordenadas.shape)

Dimensiones: (4, 2)


6) Copie el array del ejercicio anterior. Traspóngalo. Agregue ahora dos nuevos pares de coordenadas: (10.8,3.0) y (35.8, 12.0).

In [54]:
coordenadas_copia = np.array([
    [1.33, 4.5],
    [30.0, 10.7],
    [70.2, 0.5]
])

In [55]:
coordenadas_T = coordenadas_copia.T
coordenadas_T

array([[ 1.33, 30.  , 70.2 ],
       [ 4.5 , 10.7 ,  0.5 ]])

In [56]:
# el axis es 1 porque transpusimos la matriz, en vez de ser cero
coordenadas_final = np.append(coordenadas_T, [[10.8, 3.0], [35.8, 12.0]], axis = 1)

In [57]:
coordenadas_final

array([[ 1.33, 30.  , 70.2 , 10.8 ,  3.  ],
       [ 4.5 , 10.7 ,  0.5 , 35.8 , 12.  ]])

## Parte 2: Exploración y Minería de Datos

In [59]:
df = pd.read_csv('NucleosPoblacion.csv')

1) ¿Cuántos Municipios tienen más de 100000 habitantes?

2) Realice una gráfica de barras sobre la polbación de cada ciudad, ordenela de menor a mayo y responda:
    a) ¿Cuál es la segunda ciudad más poblada?
    b) ¿Qué posición ocupa Granada en el ranking de las ciudades más pobladas?

3) ¿Cuántos municipios de Extremadura tienen más de 5000 habitantes?

4) ¿Cuál es el municipio situado más al Norte? (Usar el valor de la coordenada "Y" que representa la latitud en grados). Proporcione también la provincia a la que pertenece y su población.

5) Obtenga la media, mediana, desviación estándar, valor máximo y valor mínimo de la población de los municipios de la provincia de Granada.

6) Realice un histograma con la población de los Municipios para cada una de las provincias.

7) Seleccione al azar cincuenta municipios diferentes de entre los diponibles en el archivo. Asegúrese de que no se repitan. ¿Luego calcule el promedio de la población y la desviación estándar de esto 50 municipios?.

8) Determine los nombres de los Municipios más cercano y más lejano a Madrid. Para ello debe calcular la distancia en todos ellos y Madrid. No considere a Madrid en el análisis ya que la distancia sería cero.